/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
void sub_1030();
void sub_1040();
void sub_1050();
void sub_1060();
void sub_1070();
void sub_1080();
void sub_1090();
void sub_10A0();
void sub_10B0();
void sub_10C0();
// int _cxa_finalize(void *);
// void free(void *ptr);
// int puts(const char *s);
// int printf(const char *format, ...);
// ssize_t read(int fd, void *buf, size_t nbytes);
// void *malloc(size_t size);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// int atoi(const char *nptr);
// void __noreturn exit(int status);
// char *strdup(const char *s);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
void *sub_11B0();
__int64 sub_11E0(void); // weak
void *sub_1220();
__int64 sub_1260();
int setup();
__int64 __fastcall read_data(void *a1, unsigned int a2);
int get_choice();
unsigned __int64 add_user();
int delete_user();
int edit_bio();
int print_user();
int menu();
void __fastcall __noreturn main(const char *a1, char **a2, char **a3);
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// char *strdup(const char *s);
// int __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

void *off_4008 = &off_4008; // idb
_UNKNOWN unk_4010; // weak
FILE *stdout; // idb
FILE *stdin; // idb
FILE *stderr; // idb
char byte_4048; // weak
_QWORD qword_4060[10]; // weak


//----- (0000000000001000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 4118: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001030) ----------------------------------------------------
void sub_1030()
{
  sub_1020();
}

//----- (0000000000001040) ----------------------------------------------------
void sub_1040()
{
  sub_1020();
}

//----- (0000000000001050) ----------------------------------------------------
void sub_1050()
{
  sub_1020();
}

//----- (0000000000001060) ----------------------------------------------------
void sub_1060()
{
  sub_1020();
}

//----- (0000000000001070) ----------------------------------------------------
void sub_1070()
{
  sub_1020();
}

//----- (0000000000001080) ----------------------------------------------------
void sub_1080()
{
  sub_1020();
}

//----- (0000000000001090) ----------------------------------------------------
void sub_1090()
{
  sub_1020();
}

//----- (00000000000010A0) ----------------------------------------------------
void sub_10A0()
{
  sub_1020();
}

//----- (00000000000010B0) ----------------------------------------------------
void sub_10B0()
{
  sub_1020();
}

//----- (00000000000010C0) ----------------------------------------------------
void sub_10C0()
{
  sub_1020();
}

//----- (0000000000001180) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, 0, 0, a3, &v5);
  __halt();
}
// 118A: positive sp value 8 has been found
// 1191: variable 'v3' is possibly undefined

//----- (00000000000011B0) ----------------------------------------------------
void *sub_11B0()
{
  return &unk_4010;
}

//----- (00000000000011E0) ----------------------------------------------------
__int64 sub_11E0()
{
  return 0;
}
// 11E0: using guessed type __int64 sub_11E0();

//----- (0000000000001220) ----------------------------------------------------
void *sub_1220()
{
  void *result; // rax

  if ( !byte_4048 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(off_4008);
    result = sub_11B0();
    byte_4048 = 1;
  }
  return result;
}
// 4048: using guessed type char byte_4048;

//----- (0000000000001260) ----------------------------------------------------
// attributes: thunk
__int64 sub_1260()
{
  return sub_11E0();
}
// 11E0: using guessed type __int64 sub_11E0(void);

//----- (0000000000001269) ----------------------------------------------------
int setup()
{
  setvbuf(stdin, 0, 2, 0);
  setvbuf(stdout, 0, 2, 0);
  return setvbuf(stderr, 0, 2, 0);
}

//----- (00000000000012CE) ----------------------------------------------------
__int64 __fastcall read_data(void *a1, unsigned int a2)
{
  int v3; // [rsp+1Ch] [rbp-4h]

  v3 = read(0, a1, a2);
  if ( v3 <= 0 )
  {
    puts("Error reading input");
    exit(-1);
  }
  if ( *((_BYTE *)a1 + v3 - 1) == 0xA )
    *((_BYTE *)a1 + v3 - 1) = 0;
  return (unsigned int)v3;
}

//----- (0000000000001346) ----------------------------------------------------
int get_choice()
{
  char nptr[24]; // [rsp+0h] [rbp-20h] BYREF
  unsigned __int64 v2; // [rsp+18h] [rbp-8h]

  v2 = __readfsqword(0x28u);
  read_data(nptr, 16);
  return atoi(nptr);
}
// 12CE: using guessed type __int64 __fastcall sub_12CE(_QWORD, _QWORD);

//----- (0000000000001394) ----------------------------------------------------
unsigned __int64 add_user()
{
  __int64 v0; // rbx
  int i; // [rsp+8h] [rbp-128h]
  int idx; // [rsp+Ch] [rbp-124h]
  char s[264]; // [rsp+10h] [rbp-120h] BYREF
  unsigned __int64 v5; // [rsp+118h] [rbp-18h]

  v5 = __readfsqword(0x28u);
  idx = -1;
  for ( i = 0; i <= 9; ++i )
  {
    if ( !qword_4060[i] )
    {
      idx = i;
      break;
    }
  }
  if ( idx == -1 )
  {
    puts("User limit reached");
  }
  else
  {
    qword_4060[idx] = malloc(0x68u);
    if ( !qword_4060[idx] )
    {
      puts("Malloc failed");
      exit(-1);
    }
    printf("Name: ");
    read_data((void *)qword_4060[idx], 0x20u);
    printf("Address: ");
    read_data((void *)(qword_4060[idx] + 0x20LL), 0x40u);
    printf("Bio: ");
    read_data(s, 256u);
    v0 = qword_4060[idx];
    *(_QWORD *)(v0 + 96) = strdup(s);
    printf("User added at index %d\n", idx);
  }
  return v5 - __readfsqword(0x28u);
}

//----- (000000000000158D) ----------------------------------------------------
int delete_user()
{
  unsigned int choice; // [rsp+Ch] [rbp-4h]

  printf("Index: ");
  choice = get_choice();
  if ( choice > 9 || !qword_4060[choice] )
    return puts("Invalid index");
  free(*(void **)(qword_4060[choice] + 96LL));
  free((void *)qword_4060[choice]);
  qword_4060[choice] = 0;
  return puts("User deleted");
}
// 4060: using guessed type _QWORD qword_4060[10];

//----- (0000000000001665) ----------------------------------------------------
int edit_bio()
{
  int choice; // [rsp+Ch] [rbp-4h]

  printf("Index: ");
  choice = get_choice();
  if ( (unsigned int)choice > 9 || !qword_4060[choice] )
    return puts("Invalid index");
  printf("Old Bio: %s\n", *(const char **)(qword_4060[choice] + 96LL));
  printf("New Bio: ");
  read_data(*(void **)(qword_4060[choice] + 96LL), 0x100u);
  return puts("Bio updated");
}
// 4060: using guessed type _QWORD qword_4060[10];

//----- (000000000000174D) ----------------------------------------------------
int print_user()
{
  unsigned int choice; // [rsp+Ch] [rbp-4h]

  printf("Index: ");
  choice = get_choice();
  if ( choice > 9 || !qword_4060[choice] )
    return puts("Invalid index");
  printf("Name: %s\n", (const char *)qword_4060[choice]);
  printf("Address: %s\n", (const char *)(qword_4060[choice] + 32LL));
  return printf("Bio: %s\n", *(const char **)(qword_4060[choice] + 96LL));
}
// 4060: using guessed type _QWORD qword_4060[10];

//----- (000000000000184E) ----------------------------------------------------
int menu()
{
  puts("----------------------");
  puts("1. Add User");
  puts("2. Edit Bio");
  puts("3. Delete User");
  puts("4. Print User");
  puts("5. Exit");
  return printf("Choice: ");
}

//----- (00000000000018C7) ----------------------------------------------------
void __fastcall __noreturn main(const char *a1, char **a2, char **a3)
{
  setup();
  while ( 1 )
  {
    menu(a1, a2);
    switch ( (unsigned int)get_choice() )
    {
      case 1u:
        add_user();
        break;
      case 2u:
        edit_bio();
        break;
      case 3u:
        delete_user();
        break;
      case 4u:
        print_user();
        break;
      case 5u:
        exit(0);
      default:
        a1 = "Invalid choice";
        puts("Invalid choice");
        break;
    }
  }
}
// 1346: using guessed type __int64 sub_1346(void);
// 1394: using guessed type __int64 sub_1394(void);
// 158D: using guessed type __int64 sub_158D(void);
// 1665: using guessed type __int64 sub_1665(void);
// 174D: using guessed type __int64 sub_174D(void);
// 184E: using guessed type __int64 __fastcall sub_184E(_QWORD, _QWORD);

//----- (000000000000196C) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=51 queued=27 decompiled=27 lumina nreq=0 worse=0 better=0
// ALL OK, 27 function(s) have been successfully decompiled
